// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Genre struct {
	GenreID int32  `json:"genre_id"`
	Name    string `json:"name"`
}

type Movie struct {
	MovieID     int32     `json:"movie_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	PosterUrl   string    `json:"poster_url"`
	GenreID     int32     `json:"genre_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Reservation struct {
	ReservationID int64     `json:"reservation_id"`
	UserID        int64     `json:"user_id"`
	ShowtimeID    int32     `json:"showtime_id"`
	SeatID        int32     `json:"seat_id"`
	ReservedAt    time.Time `json:"reserved_at"`
}

// This table represents the fixed seat layout
type Seat struct {
	SeatID    int32     `json:"seat_id"`
	Row       int32     `json:"row"`
	Number    int32     `json:"number"`
	CreatedAt time.Time `json:"created_at"`
}

type Showtime struct {
	ShowtimeID int32            `json:"showtime_id"`
	MovieID    int32            `json:"movie_id"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	Price      pgtype.Numeric   `json:"price"`
	CreatedAt  time.Time        `json:"created_at"`
}

type User struct {
	UserID         int64     `json:"user_id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
}
