// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelReservation(ctx context.Context, arg CancelReservationParams) error
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShowtime(ctx context.Context, arg CreateShowtimeParams) (Showtime, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMovie(ctx context.Context, movieID int32) error
	DeleteShowtime(ctx context.Context, showtimeID int32) error
	GetMovie(ctx context.Context, movieID int32) (Movie, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetShowtime(ctx context.Context, showtimeID int32) (Showtime, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID int64) (User, error)
	ListAllSeats(ctx context.Context) ([]Seat, error)
	ListAvailableSeatsForShowtime(ctx context.Context, showtimeID int32) ([]Seat, error)
	ListGenres(ctx context.Context) ([]Genre, error)
	ListMovies(ctx context.Context, arg ListMoviesParams) ([]Movie, error)
	ListReservationsByShowtime(ctx context.Context, showtimeID int32) ([]ListReservationsByShowtimeRow, error)
	ListReservationsByUser(ctx context.Context, userID int64) ([]ListReservationsByUserRow, error)
	ListSeatsForShowtime(ctx context.Context, showtimeID int32) ([]ListSeatsForShowtimeRow, error)
	ListShowtimesBetween(ctx context.Context, arg ListShowtimesBetweenParams) ([]ListShowtimesBetweenRow, error)
	ListShowtimesByDate(ctx context.Context, startTime pgtype.Timestamp) ([]ListShowtimesByDateRow, error)
	ReserveSeat(ctx context.Context, arg ReserveSeatParams) (Reservation, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error)
}

var _ Querier = (*Queries)(nil)
