// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: seat.sql

package db

import (
	"context"
)

const listAllSeats = `-- name: ListAllSeats :many
SELECT seat_id, row, number, created_at FROM seats
ORDER BY row, number
`

func (q *Queries) ListAllSeats(ctx context.Context) ([]Seat, error) {
	rows, err := q.db.Query(ctx, listAllSeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seat{}
	for rows.Next() {
		var i Seat
		if err := rows.Scan(
			&i.SeatID,
			&i.Row,
			&i.Number,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
